### ISSUE TITLE
Under which license? MIT like A-Frame?

### ISSUE THREAD

**Issue by nuess0r** [dpa99c/stereoscopic-slideshow#2]
Hi

I currently fiddle around with your great project. Finally someone who made it possible to view stereo slides on modern devices!

My current goal is to combine your project with an existing photo gallery plugin for the wiki I personally use (I use it as a simple content management system). The plugin code is licensed under GPL-2.0. So before I'm starting to combine stuff I wanted to ask what license applies for your stereoscopic-slideshow?

The A-Frame project is licensed under MIT (https://github.com/aframevr/aframe/blob/master/LICENSE). Using MIT code inside a GPL-2.0 project is OK to my understanding: https://en.wikipedia.org/wiki/License_compatibility#Compatibility_of_FOSS_licenses

**Comment by dpa99c** [comment]
I've added an MIT License to clarify - hope that's OK

**Comment by nuess0r** [comment]
Thanks a lot for your quick response. I'll let you know, when there is something working to show.
